### ISSUE TITLE
Create giftcard option frontend

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#125]
## Goal

Create and option to purchase a giftcard that matches one of the sizes of family trees we have.

## Requirements

- Create design in figma.
- Approve design from other developers.
- Implement design in the front end.
- Include e2e tests for the front end use of giftcards. 
- Create basket item for giftcard 
- Create checkout item for giftcard 
- Refactor components > items
    should have: 
      - folder for basket items
      - folder for checkout items 
      - folder for design items

### Design

Create the design in figma first, then follow the design after approval.

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-92))
