### ISSUE TITLE
Implement backend for giftcard

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#126]
## Goal

Connect the backend and frontend to work with purchasing of giftcards

## Requirements

Link the backend to display the giftcard:
- giftcard page 
- basket page 
- checkout page 
- order confirmation email 

Add tests for the backend. 

Add new giftcard type interface, enums etc. (@Kwandes will be better at describing this issue)

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-91))
