### ISSUE TITLE
Update the banner to curve

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#167]
## Goal

People have shown great interrest in having the old curving banner back. Therefore, we need to re-add that feature in the new design canvas. 

Requirements: 
- change the banner design to the curvy design.
- make the input text of the banner show in a curvy manner on the banner.

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-85))
