### ISSUE TITLE
Add event receiver in navbar

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#170]
## Goal

Make navbar update items in basket without reloading page. 

## Requirements 

- add event emitters to all components that add items to basket 
>  - Add to basket modal when adding to basket. 
>  - Basket page / when deleting, increasing or decreasing item quantity.
- add output function in navbar to update the itemsInBasket number.

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-95))
