### ISSUE TITLE
Send a welcome email to newsletter subscribers

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#177]
## Goal

When the system gets a new subscriber to the newsletter, an automatic introduction email should be sent to the new subscriber. This email should include a unique generated discount code that gives 10% off and only works once. 

## Requirements 

- Create a method that automatically sends the introduction email to the new newsletter subscriber. 

- Create a method in the api that generates a discount code:
1. 10% off
2. can only be used once
3. unique
- Create an email .html file with an introduction text to treecreate. It should include: 
1. localisation dk/en
2. the generated discount
3. images through thymeleaf

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-77))
