### ISSUE TITLE
Implement a healthcheck endpoint

### ISSUE THREAD

**Issue by Kwandes** [treecreate/webstore#18]
Implement an endpoint in the API that, when called, returns the running version of the API along with its status (if all of the modules are initialized properly, there is a database connection etc)

- The endpoint should be of type GET, `/healthcheck`
- The endpoint should return status 200
- The endpoint must be documented with Swagger UI (might have to wait for Swagger UI to be implemented)
- The endpoint must have tests

**Comment by Kwandes** [comment]
You can use [My Sonito project](https://github.com/Kwandes/sonito/tree/main/apps/api) as inspiration for the structure

**Comment by Kwandes** [comment]
Notification Showcase
This should give @IroniX2 a notification

**Comment by Kwandes** [comment]
@IroniX2 Test number two

**Comment by DryDish** [comment]
no
