### ISSUE TITLE
Setup semantic versioning / branching

### ISSUE THREAD

**Issue by Kwandes** [treecreate/webstore#2]
After implemented #1 
___

Setup automated semantic versioning that defines the next version of the application after analyzing commit messages following Angular commit message conventions. This should be done after finishing #1.

#### Before setting it up
- for Nx generated project, make sure to have a flat folder structure, meaning place workspace files to the root directory.
   `package.json` has to be in the root directory

follow [docs I wrote about semantic-versioning setup](https://github.com/shieldapp/sturdy-giggle/blob/development/docs/semantic-release-setup/README.md#semantic-release-setup) or [official documentation](https://github.com/semantic-release/semantic-release)

**Comment by CristiPV** [comment]
I love how you moved it to In progress and then you gave up

**Comment by Kwandes** [comment]
Moving to milestone [Continous Integration and Delivery](https://github.com/treecreate/webstore/milestone/2) because of complexity and unfinished third-party documentation

**Comment by Kwandes** [comment]
Closing due to insufficient resources
It will be developed at a later date
