### ISSUE TITLE
Add hasSeenIntro to cookies

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#218]
## Goal

Add a cookie that tracks if a user has seen the intro or not.

## Requirements

The first time a user goes to product page he/she is presented with the introduction screen. 
Then the cookies should track that the user has seen the intro.

1. add an if statement to check cookies and see if user has seen the intro before 
2. If user has seen it, dont show it
3. else show the intro 
4. Add a question mark button in product page, possibly in options, that when clicked, opens the intro modal.

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-84))
