### ISSUE TITLE
Fix large font

### ISSUE THREAD

**Issue by Teodor25** [treecreate/webstore#226]
## Goal

Fixing the large font option

## Requirements

Have large font text be limited to only show 12 chars or so. example: 

input (normal): 
12345678
910111213

input (large font active): 
12345678

when disabling the large font, the input should go back to showing all chars (12345678910111213) in two lines.

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-82))
