### ISSUE TITLE
Order info: saved amount going into minus

### ISSUE THREAD

**Issue by DryDish** [treecreate/webstore#261]
## Goal

Fix discount code going into minus if no discount code is provided

## Requirements

* Needs to no go into minus if no code is provided
* Need to ensure that the discount code is counted properly if one is applied AND shipping is payed

## Screenshot 

![image](https://user-images.githubusercontent.com/57399961/143234046-ed3b9113-5127-46da-a6cf-f1876479aa92.png)

**Comment by Kwandes** [comment]
Closed due to moving issues to Jira ([issue](https://treecreate.atlassian.net/browse/TC-76))
